/** 타닥클래스 강의 카탈로그 — sync 스크립트·시드·어드민 공통 */
const COURSES = [
  {
    slug: 'capcut-beginner-free',
    title: '캡컷 초보자반',
    category: '캡컷 PRO',
    description: '캡컷을 처음 시작하는 분을 위한 무료 입문 강의입니다.',
    thumbnail_icon: 'ti-device-mobile',
    thumb_style: 'light',
    price: 0,
    sale_price: 0,
    badge: 'FREE',
    sort_order: 1,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'recorded',
  },
  {
    slug: 'capcut-pro-basic',
    title: '캡컷 PRO 기초반',
    category: '캡컷 PRO',
    description: '캡컷 PRO의 핵심 기능과 기본 편집 워크플로를 익히는 기초 과정입니다.',
    thumbnail_icon: 'ti-device-mobile',
    thumb_style: 'dark',
    price: 55000,
    sale_price: 55000,
    badge: null,
    sort_order: 2,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'recorded',
  },
  {
    slug: 'capcut-pro-fast-edit',
    title: '캡컷 PRO 초고속 영상제작반',
    category: '캡컷 PRO',
    description: '실무 속도로 영상을 기획·촬영·편집·납품까지 완성하는 초고속 제작 과정입니다.',
    thumbnail_icon: 'ti-bolt',
    thumb_style: 'light',
    price: 350000,
    sale_price: 350000,
    badge: 'BEST',
    sort_order: 3,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'recorded',
  },
  {
    slug: 'capcut-pro-monetize',
    title: '캡컷 PRO 영상납품 수익화',
    category: '캡컷 PRO',
    description: '영상 납품 실무와 수익화 전략을 배우는 심화 과정입니다.',
    thumbnail_icon: 'ti-currency-won',
    thumb_style: 'dark',
    price: 1250000,
    sale_price: 1250000,
    badge: null,
    sort_order: 4,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'recorded',
  },
  {
    slug: 'premiere-beginner',
    title: '프리미어 프로 초보자반',
    category: '프리미어 프로',
    description: '프리미어 프로 입문자를 위한 기초 편집 강의입니다.',
    thumbnail_icon: 'ti-cut',
    thumb_style: 'light',
    price: 75000,
    sale_price: 75000,
    badge: null,
    sort_order: 5,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'recorded',
  },
  {
    slug: 'premiere-influencer-vlog',
    title: '프리미어 프로 초고속 영상제작반 — 인플루언서 브이로그/쇼츠',
    category: '프리미어 프로',
    description: '브이로그·쇼츠 제작에 특화된 프리미어 프로 실전 과정입니다.',
    thumbnail_icon: 'ti-video',
    thumb_style: 'dark',
    price: 250000,
    sale_price: 250000,
    badge: 'NEW',
    sort_order: 6,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'recorded',
  },
  {
    slug: 'premiere-multicam',
    title: '프리미어 프로 멀티캠 편집반 — 중형 프로덕션 편집기술전수반',
    category: '프리미어 프로',
    description: '멀티캠·중형 프로덕션 현장 편집 기술을 전수하는 심화 과정입니다.',
    thumbnail_icon: 'ti-camera',
    thumb_style: 'light',
    price: 2500000,
    sale_price: 2500000,
    badge: null,
    sort_order: 7,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'recorded',
  },
  {
    slug: 'video-planning-offline',
    title: '영상기획 및 구현반 (only offline)',
    category: '오프라인',
    description: '오프라인으로 진행되는 영상 기획·촬영·구현 통합 과정입니다.',
    thumbnail_icon: 'ti-map-pin',
    thumb_style: 'dark',
    price: 1000000,
    sale_price: 1000000,
    badge: 'OFFLINE',
    sort_order: 8,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'offline',
    is_offline: 1,
  },
  {
    slug: 'ai-cardnews-basic',
    title: 'AI 카드뉴스 기초반',
    category: 'AI·상세페이지',
    description: 'AI 도구를 활용해 카드뉴스를 기획·제작하는 입문 과정입니다.',
    thumbnail_icon: 'ti-photo',
    thumb_style: 'light',
    price: 33000,
    sale_price: 33000,
    badge: null,
    sort_order: 9,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'recorded',
  },
  {
    slug: 'ai-cardnews-advanced',
    title: 'AI 카드뉴스 중급반 / 자동화',
    category: 'AI·상세페이지',
    description: '카드뉴스 제작 자동화와 중급 워크플로를 다루는 과정입니다.',
    thumbnail_icon: 'ti-robot',
    thumb_style: 'dark',
    price: 333000,
    sale_price: 333000,
    badge: null,
    sort_order: 10,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'recorded',
  },
  {
    slug: 'ai-detail-page-monetize',
    title: 'AI 상세페이지 제작 및 납품 수익화',
    category: 'AI·상세페이지',
    description: 'AI로 상세페이지를 제작하고 납품·수익화까지 연결하는 실전 과정입니다.',
    thumbnail_icon: 'ti-layout',
    thumb_style: 'light',
    price: 550000,
    sale_price: 550000,
    badge: 'BEST',
    sort_order: 11,
    rating: 0,
    review_count: 0,
    student_count: 0,
    is_published: 1,
    course_type: 'recorded',
  },
]

const TARGET_SLUGS = new Set(COURSES.map(c => c.slug))

function sortCourses(list) {
  return [...list].sort((a, b) => (a.sort_order ?? 999) - (b.sort_order ?? 999))
}

function gridRowLabel(count) {
  const rows = []
  for (let i = 0; i < count; i += 3) rows.push(Math.min(3, count - i))
  return rows.join(' / ')
}

module.exports = { COURSES, TARGET_SLUGS, sortCourses, gridRowLabel }
