"""캡컷 9.x가 실제로 생성하는 텍스트 트랙/세그먼트/소재 구조 (실측 템플릿).

캡컷(9.0.0.3851)에서 직접 자막을 추가해 저장한 draft_content.json에서
그대로 떠온 구조다. 이 구조를 바이트 수준으로 복제(ID/텍스트/시간만 교체)한
세그먼트는 캡컷이 정상 인식함을 실험으로 확인했다 (0627_test4 실험).

pycapcut(0.0.3)은 구버전 캡컷(6.x) 구조로 자막을 만들기 때문에 최신 캡컷이
트랙을 통째로 무시하고 자동저장 때 삭제한다 — 그래서 사용하지 않는다.
"""

from __future__ import annotations

TRACK_TPL: dict = {
    "id": "",
    "type": "text",
    "segments": [],
    "flag": 0,
    "attribute": 0,
    "name": "",
    "is_default_name": False,
}

# 실측 세그먼트 전체(51개 필드). id/material_id/extra_material_refs/
# target_timerange/clip.transform.y/track_render_index만 라인별로 교체한다.
SEGMENT_TPL: dict = {
    "id": "",
    "source_timerange": None,
    "target_timerange": {"start": 0, "duration": 0},
    "render_timerange": {"start": 0, "duration": 0},
    "desc": "",
    "state": 0,
    "speed": 1.0,
    "is_loop": False,
    "is_tone_modify": False,
    "reverse": False,
    "intensifies_audio": False,
    "cartoon": False,
    "volume": 1.0,
    "last_nonzero_volume": 1.0,
    "clip": {
        "scale": {"x": 1.0, "y": 1.0},
        "rotation": 0.0,
        "transform": {"x": 0.0, "y": 0.0},
        "flip": {"vertical": False, "horizontal": False},
        "alpha": 1.0,
    },
    "uniform_scale": {"on": True, "value": 1.0},
    "material_id": "",
    "extra_material_refs": [],
    "render_index": 14000,
    "keyframe_refs": [],
    "enable_lut": False,
    "enable_adjust": False,
    "enable_hsl": False,
    "visible": True,
    "group_id": "",
    "enable_color_curves": True,
    "enable_hsl_curves": True,
    "track_render_index": 1,
    "hdr_settings": None,
    "enable_color_wheels": True,
    "track_attribute": 0,
    "is_placeholder": False,
    "template_id": "",
    "enable_smart_color_adjust": False,
    "template_scene": "default",
    "common_keyframes": [],
    "caption_info": None,
    "responsive_layout": {
        "enable": False,
        "target_follow": "",
        "size_layout": 0,
        "horizontal_pos_layout": 0,
        "vertical_pos_layout": 0,
    },
    "enable_color_match_adjust": False,
    "enable_color_correct_adjust": False,
    "enable_adjust_mask": False,
    "raw_segment_id": "",
    "lyric_keyframes": None,
    "enable_video_mask": True,
    "digital_human_template_group_id": "",
    "color_correct_alg_result": "",
    "source": "segmentsourcenormal",
    "enable_mask_stroke": False,
    "enable_mask_shadow": False,
    "enable_color_adjust_pro": False,
    "segment_color_tag": "",
}

# 실측 텍스트 소재 전체(124개 필드). id/content/font_size/text_size/
# font_path/border_width/check_flag만 라인별로 교체한다.
MATERIAL_TPL: dict = {
    "recognize_task_id": "",
    "id": "",
    "name": "",
    "recognize_text": "",
    "recognize_model": "",
    "punc_model": "",
    "type": "text",
    "content": "",
    "base_content": "",
    "words": {"start_time": [], "end_time": [], "text": []},
    "current_words": {"start_time": [], "end_time": [], "text": []},
    "global_alpha": 1.0,
    "combo_info": {"text_templates": []},
    "caption_template_info": {
        "resource_id": "",
        "third_resource_id": "",
        "resource_name": "",
        "category_id": "",
        "category_name": "",
        "effect_id": "",
        "request_id": "",
        "path": "",
        "is_new": False,
        "source_platform": 0,
    },
    "layer_weight": 1,
    "letter_spacing": 0.0,
    "text_curve": None,
    "text_loop_on_path": False,
    "offset_on_path": 0.0,
    "enable_path_typesetting": False,
    "text_exceeds_path_process_type": 0,
    "text_typesetting_paths": None,
    "text_typesetting_paths_file": "",
    "text_typesetting_path_index": 0,
    "line_spacing": 0.02,
    "has_shadow": False,
    "shadow_color": "",
    "shadow_alpha": 0.9,
    "shadow_smoothing": 0.45,
    "shadow_distance": 5.0,
    "shadow_point": {"x": 0.6363961030678928, "y": -0.6363961030678928},
    "shadow_angle": -45.0,
    "shadow_thickness_projection_enable": False,
    "shadow_thickness_projection_angle": 0.0,
    "shadow_thickness_projection_distance": 0.0,
    "border_alpha": 1.0,
    "border_color": "",
    "border_width": 0.08,
    "border_mode": 0,
    "style_name": "",
    "text_color": "#FFFFFF",
    "text_alpha": 1.0,
    "font_name": "",
    "font_title": "none",
    "font_size": 15.0,
    "font_path": "",
    "font_id": "",
    "font_resource_id": "",
    "initial_scale": 1.0,
    "font_url": "",
    "typesetting": 0,
    "alignment": 1,
    "line_feed": 1,
    "use_effect_default_color": True,
    "is_rich_text": False,
    "shape_clip_x": False,
    "shape_clip_y": False,
    "ktv_color": "",
    "text_to_audio_ids": [],
    "bold_width": 0.0,
    "italic_degree": 0,
    "underline": False,
    "underline_width": 0.05,
    "underline_offset": 0.22,
    "sub_type": 0,
    "check_flag": 7,
    "text_size": 30,
    "font_category_name": "",
    "font_source_platform": 0,
    "font_third_resource_id": "",
    "font_category_id": "",
    "add_type": 0,
    "operation_type": 0,
    "recognize_type": 0,
    "fonts": [],
    "background_color": "",
    "background_alpha": 1.0,
    "background_style": 0,
    "background_round_radius": 0.0,
    "background_width": 0.14,
    "background_height": 0.14,
    "background_vertical_offset": 0.0,
    "background_horizontal_offset": 0.0,
    "background_fill": "",
    "single_char_bg_enable": False,
    "single_char_bg_color": "",
    "single_char_bg_alpha": 1.0,
    "single_char_bg_round_radius": 0.3,
    "single_char_bg_width": 0.0,
    "single_char_bg_height": 0.0,
    "single_char_bg_vertical_offset": 0.0,
    "single_char_bg_horizontal_offset": 0.0,
    "font_team_id": "",
    "tts_auto_update": False,
    "text_preset_resource_id": "",
    "group_id": "",
    "preset_id": "",
    "preset_name": "",
    "preset_category": "",
    "preset_category_id": "",
    "preset_index": 0,
    "preset_has_set_alignment": False,
    "force_apply_line_max_width": False,
    "language": "",
    "relevance_segment": [],
    "original_size": [],
    "fixed_width": -1.0,
    "fixed_height": -1.0,
    "autoAdaptCanvasEnabled": False,
    "line_max_width": 0.82,
    "oneline_cutoff": False,
    "cutoff_postfix": "",
    "subtitle_template_original_fontsize": 0.0,
    "subtitle_keywords": None,
    "inner_padding": -1.0,
    "multi_language_current": "none",
    "source_from": "",
    "is_lyric_effect": False,
    "lyric_group_id": "",
    "lyrics_template": {
        "resource_id": "",
        "resource_name": "",
        "panel": "",
        "effect_id": "",
        "path": "",
        "category_id": "",
        "category_name": "",
        "request_id": "",
    },
    "is_batch_replace": False,
    "is_words_linear": False,
    "ssml_content": "",
    "subtitle_keywords_config": None,
    "sub_template_id": -1,
    "translate_original_text": "",
}

# 세그먼트의 extra_material_refs가 가리키는 애니메이션 소재 (실측).
ANIMATION_TPL: dict = {
    "id": "",
    "type": "sticker_animation",
    "animations": [],
    "multi_language_current": "none",
}
